name: Version Bumping and Changelog Update

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read Current Version
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set Version Bump Type Based on Branch
        id: set_bump_type
        run: |
          # Get the current branch name
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch name: $BRANCH_NAME"

          # Determine if it's a feature or bugfix branch
          if [[ "$BRANCH_NAME" == feature/* ]]; then
            echo "BUMP_TYPE=minor" >> $GITHUB_ENV
            echo "Feature branch detected"
          elif [[ "$BRANCH_NAME" == bugfix/* ]]; then
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
            echo "Bugfix branch detected"
          else
            echo "BUMP_TYPE=none" >> $GITHUB_ENV
            echo "No version bump needed, branch name is: $BRANCH_NAME"
          fi
          
      - name: Increment Version Based on Branch
        if: env.BUMP_TYPE != 'none'
        id: increment_version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          if [ "$BUMP_TYPE" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            echo "Minor bump started"
          elif [ "$BUMP_TYPE" == "patch" ]; then
            PATCH=$((PATCH + 1))
            echo "Patch bump started"
          fi
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > VERSION
          echo "New Version: $NEW_VERSION"

      - name: Generate Changelog
        id: generate_changelog
        run: |
          echo "## $(cat VERSION)" > changelog_temp.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD >> changelog_temp.md
          echo "" >> changelog_temp.md
          cat CHANGELOG.md >> changelog_temp.md
          mv changelog_temp.md CHANGELOG.md
          echo "Changelog updated according to the latest commits"

      - name: Commit and Push Updated Version and Changelog
        if: env.BUMP_TYPE != 'none'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add VERSION CHANGELOG.md
          git commit -m "ci: Increment version and update changelog"
          git push
          echo "Version and Changelog updated and pushed to the repository"